services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    env_file:
      - .env

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/templates/default.conf.template
    ports:
      - "80:80"
    environment:
      - BACKEND_PORT=${BACKEND_PORT}
    depends_on:
      - backend

  db:
    image: mongo