services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    env_file:
      - .env
    network_mode: host

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend/src:/app/src
    env_file:
      - .env
    network_mode: host

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/templates/default.conf.template
    environment:
      - BACKEND_PORT=${BACKEND_PORT}
      - FRONTEND_PORT=${FRONTEND_PORT}
    depends_on:
      - backend
      - frontend
      - db
    network_mode: host

  db:
    image: mongo
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongodata:/data/db
    env_file:
      - .env

volumes:
  mongodata:
    driver: local